CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'bguyot'@'%' IDENTIFIED BY '$DB_PASSWORD';
GRANT ALL PRIVILEGES ON wordpress.* TO 'bguyot'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '$DB_ROOT_PASSWORD';